apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hpa-custom.fullname" . }}
  labels:
    app: {{ include "hpa-custom.name" . }}
    app.kubernetes.io/name: {{ include "hpa-custom.name" . }}
    helm.sh/chart: {{ include "hpa-custom.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ include "hpa-custom.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "hpa-custom.name" . }}
    spec:
      containers:
      - image: luxas/autoscale-demo:v0.1.2
        name: metrics-provider
        resources:
{{ toYaml .Values.resources | indent 10 }}
      ports:
      - name: http
        port: 8080


